repos:
  - repo: local
    hooks:
      - id: vala-lint
        name: Run Vala files lint
        entry: ./tools/check-vala
        language: system
        pass_filenames: false

      - id: blp-lint
        name: Run blueprint files lint
        entry: ./tools/check-blp
        language: system
        pass_filenames: false
