option(
  'nightly',
  type: 'boolean',
  value: false
)

# Lib
option(
  'with_lib_documentation',
  type: 'boolean',
  value: false,
  description: 'Whether to build library documentation',
)
option(
  'with_lib_introspection',
  type: 'boolean',
  value: true,
  description: 'Whether to build library introspection files',
)

# GDM
option(
  'gdm_rundir',
  type: 'string',
  value: '/run/gdm',
  description: 'GDM\'s runtime directory. The dynamic gnome-initial-setup user\'s home dir is exported here',
)
option(
  'gdm',
  type: 'feature',
  value: 'auto',
  description: 'Use integration with GDM (Login to user via Gdm.Client after initial-setup done',
)

# Phrog
option(
  'phrog',
  type: 'feature',
  value: 'auto',
  description: 'Add setup env for phrog (set first-run gsetting and unset in the end',
)

# Keyboard
option(
  'ibus',
  type: 'feature',
  value: 'auto'
)

# User
option(
  'password_check_backend',
  type: 'combo',
  choices: ['passwdqc', 'pwquality', 'both'],
  value : 'passwdqc'
)

# Software
option(
  'with_software_tuner_plugin',
  type: 'feature',
  value: 'auto',
  description: 'Build tuner plugin with software plugin functionality'
)

# Tests
option(
  'install_tests',
  type: 'feature',
  value: 'disabled',
  description: 'Install tests plugins or not'
)
