name: Build image

on:
  workflow_dispatch:

env:
  LOCAL_BUILD_NAME: localhost
  REGISTRY: altlinux.space
  PARENT_IMAGE: altlinux.space/alt-atomic/minimal/phosh/nightly:latest

jobs:
  build:
    name: Build image
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/actions/runner/containers:sisyphus
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build sisyphus default image
        run: |
          podman build \
            --tag $LOCAL_BUILD_NAME \
            --platform linux/amd64 \
            --build-arg IMAGE=$PARENT_IMAGE \
            --file ./test-atomic/Containerfile \
            .

      # - name: Rechunk image
      #   uses: alt-atomic/actions/rechunk@main
      #   id: rechunk
      #   with:
      #     ref: ${{ env.LOCAL_BUILD_NAME }}
      #     prev-ref: ${{ env.REGISTRY }}/${{ github.repository }}:latest

      - name: Push images
        uses: alt-atomic/actions/push-and-sign@main
        with:
          registry: ${{ env.REGISTRY }}
          registry-username: "<token>"
          registry-password: ${{ secrets.TOKEN }}
          image-name: alt-gnome/ready-set-test-atomic
          image-tag: latest
          local-build-name: ${{ env.LOCAL_BUILD_NAME }}
