name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'altlinux'
    tags-ignore:
      - '*'

jobs:
  lint-vala:
    name: Check vala files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  lint-blueprint:
    name: Check blueprint files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/blueprint@main

  build-doc-translation:
    name: Build, update translation and upload doc
    runs-on: als-huge
    needs:
      - lint-vala
      - lint-blueprint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.event_name == 'pull_request' && github.token || secrets.REPO_TOKEN }}

      - name: Install deps
        run: |
          apt-get update
          xargs apt-get install -y < ./build-aux/altlinux/build-deps

      - name: Setup
        run: meson setup _build -Duser_with_set_root=true -Dwith_lib_documentation=true -Dis_devel=true  -Dpassword_check_backend=both

      - name: Build
        run: meson compile -C _build

      - name: Setup git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@altlinux.space"
          git config --global --add safe.directory '*'

      - name: Update pot file for Weblate
        if: github.event_name != 'pull_request'
        run: |
          has_real_changes() {
            git diff --cached -U0 | grep -E '^[+-]' \
              | grep -Ev '^[+-]{3}' \
              | grep -Ev '^[+-]["#]' \
              | grep -q '.'
          }

          ./po/update_potfiles

          git add .
          git commit -m "i18n: Update POTFILES" || true

          meson compile -C _build ready-set-pot
          git add .

          if has_real_changes; then
            git commit -m "i18n: Update .pot file" || true

            meson compile -C _build ready-set-update-po

            git add po/*.po
            git commit -m "i18n: Update .po files" || true
          else
            git reset --hard
          fi

          git push

      - name: Deploy pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/lib/doc/ready-set-vala

  get-release:
    name: Get release for RPM package
    runs-on: als-tiny

    outputs:
      release: ${{ steps.get_release.outputs.release }}
    steps:
      - name: Get release
        id: get_release
        run: |
          echo "release=$(date +%s)" >> $FORGEJO_OUTPUT

  rpm-build-amd64:
    name: RPM build for ${{ matrix.branch }}.amd64 and uploading
    runs-on: als-huge
    container:
      image: altlinux.space/actions/runner/hasherc:sisyphus

    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
    needs:
      - lint-vala
      - lint-blueprint
      - get-release
      - build-doc-translation

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build
        run: |
          ./build-aux/altlinux/prepare ${{ needs.get-release.outputs.release }}
          git add .

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: ${{ matrix.branch }}
          arch: amd64

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/ready-set/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: ready-set-nightly/${{ github.ref_name }}/${{ matrix.branch }}

  rpm-build-arm64:
    name: RPM build for ${{ matrix.branch }}.arm64 and uploading
    runs-on: self-hosted-arm64-huge
    container:
      image: altlinux.space/actions/runner/hasherc:sisyphus

    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
    needs:
      - lint-vala
      - lint-blueprint
      - get-release
      - build-doc-translation

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build
        run: |
          ./build-aux/altlinux/prepare ${{ needs.get-release.outputs.release }}
          git add .

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: ${{ matrix.branch }}
          arch: arm64

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/ready-set/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: ready-set-nightly/${{ github.ref_name }}/${{ matrix.branch }}


  build-test-image:
    name: Build ${{ matrix.denviron }} image
    runs-on: als-huge
    strategy:
      matrix:
        denviron:
          - phrog
          - gnome
        include:
          - denviron: phrog
            image: altlinux.space/alt-atomic/minimal/phosh/nightly:latest
          - denviron: gnome
            image: altlinux.space/alt-atomic/onyx/nightly:latest

    needs:
      - rpm-build-amd64
    if: github.event_name != 'pull_request'
    env:
      LOCAL_BUILD_NAME: localhost/image
      REGISTRY: altlinux.space
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build sisyphus default image
        run: |
          podman build \
            --tag $LOCAL_BUILD_NAME \
            --platform linux/amd64 \
            --build-arg IMAGE=${{ matrix.image }} \
            --build-arg PKG_GROUP=${{ github.ref_name }} \
            --file ./test-atomic/${{ matrix.denviron }}/Containerfile \
            --label org.altlinux.installer.has-initial-setup=true \
            .

      - name: Push images
        uses: alt-atomic/actions/push-and-sign@main
        with:
          registry: ${{ env.REGISTRY }}
          registry-username: "<token>"
          registry-password: ${{ secrets.TOKEN }}
          image-name: alt-gnome/ready-set-test-atomic/${{ github.ref_name }}
          image-tag: ${{ matrix.denviron }}
          local-build-name: ${{ env.LOCAL_BUILD_NAME }}
