name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  lint-vala:
    name: Check vala files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  lint-blueprint:
    name: Check blueprint files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/blueprint@main

  build-doc-translation:
    name: Build, update translation and upload doc
    runs-on: als-huge
    container: registry.altlinux.org/sisyphus/node:latest
    needs:
      - lint-vala
      - lint-blueprint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.event_name == 'pull_request' && github.token || secrets.REPO_TOKEN }}

      - name: Setup
        run: make setup-ci

      - name: Build
        run: make compile

      - name: Test
        run: make test

      - name: Setup git
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name "ReadySet Helper Bot"
          git config --global user.email "ready-set-helper-bot@noreply.altlinux.space"
          git config --global --add safe.directory '*'

      - name: Update pot file for Weblate
        if: github.event_name != 'pull_request'
        run: |
          has_real_changes() {
            git diff --cached -U0 | grep -E '^[+-]' \
              | grep -Ev '^[+-]{3}' \
              | grep -Ev '^[+-]["#]' \
              | grep -q '.'
          }

          ./po/update_potfiles

          git add .
          git commit -m "i18n: Update POTFILES" || true

          meson compile -C _build ready-set-pot
          git add .

          if has_real_changes; then
            git commit -m "i18n: Update .pot file" || true

            meson compile -C _build ready-set-update-po

            git add po/*.po
            git commit -m "i18n: Update .po files" || true
          else
            git reset --hard
          fi

          git push

      - name: Deploy pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/lib/doc/ready-set-vala

  get-release:
    name: Get release for RPM package
    runs-on: als-tiny
    if: github.event_name != 'pull_request'

    outputs:
      release: ${{ steps.get_release.outputs.release }}
    steps:
      - name: Get release
        id: get_release
        run: |
          echo "release=$(date +%s)" >> $FORGEJO_OUTPUT

  rpm-build:
    if: github.event_name != 'pull_request'
    name: RPM build for ${{ matrix.branch }}.${{ matrix.arch }} and uploading
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-security/${{ matrix.branch }}/hasher:latest

    strategy:
      matrix:
        branch:
          - sisyphus
          # - p11
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: als-huge
          - arch: arm64
            runner: self-hosted-arm64-huge

    needs:
      - lint-vala
      - lint-blueprint
      - get-release
      - build-doc-translation

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build
        run: |
          ./build-aux/altlinux/prepare ${{ needs.get-release.outputs.release }}
          git add .

      - name: Build
        run: |
          gear-hsh --commit --no-sisyphus-check=gpg,packager

      - uses: actions/upload-rpm-action@7ed97151a2a1f53a5b97f8a9f20778f771bbae59
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/hasher/repo
          token: ${{ secrets.TOKEN }}
          group: ready-set-nightly/${{ matrix.branch }}

  build-test-image:
    name: Build ${{ matrix.denviron }} image
    runs-on: als-huge
    strategy:
      matrix:
        denviron:
          - gnome
          - phosh

    needs:
      - rpm-build
    if: github.event_name != 'pull_request'
    env:
      LOCAL_BUILD_NAME: localhost/image
      REGISTRY: altlinux.space
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check build possible
        id: check
        run: |
          if skopeo inspect docker://${{ matrix.image }} > /dev/null 2>&1; then
            echo "exists=yes" >> $GITHUB_OUTPUT
          else
            echo "exists=no" >> $GITHUB_OUTPUT
          fi

      - id: get_commit
        name: Get current commit
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

      - name: Build&Push image
        if: steps.check.outputs.exists == 'yes'
        uses: alt-atomic/actions/build-and-push@c882944ee9b49d04f3f2030aa47c435515a66657
        with:
          image-name: alt-gnome/ready-set-test-atomic
          image-tag: ${{ matrix.denviron }}
          containerfile-path: ./test-atomic/${{ matrix.denviron }}/Containerfile

          registry-password: ${{ secrets.TOKEN }}

          pretty-name: ReadySet Atomic test image
          version: ${{ steps.get_commit.outputs.commit }}

          extra-labels: |
            org.altlinux.installer.has-initial-setup=true

          rechunk-enabled: false
