name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  lint-vala:
    name: Check vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  lint-blueprint:
    name: Check blueprint files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/blueprint@main

  test-build:
    name: Test Build
    runs-on: alt-sisyphus
    needs:
      - lint-vala
      - lint-blueprint

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y meson vala "pkgconfig(gtk4)" "pkgconfig(libadwaita-1)" "pkgconfig(gnome-desktop-4)" "pkgconfig(gee-0.8)" "pkgconfig(accountsservice)" "pkgconfig(ibus-1.0)" "pkgconfig(pwquality)" "pkgconfig(systemd)" "pkgconfig(polkit-gobject-1)" blueprint-compiler
 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build

      - name: Build
        run: meson compile -C _build
