name: Build ALT package

on:
  workflow_dispatch:
  push:
    branches:
      - 'altlinux'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-altlinux:
    name: Build RPM for altlinux

    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/hasherc-action:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: alt-gnome/build-rpm-action@main
        name: Build RPMs

      - uses: alt-gnome/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/ready-set/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: ready-set
