name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          make lint

  build-doc:
    name: Build and upload doc
    runs-on: als-huge
    container: registry.altlinux.org/sisyphus/node:latest
    needs:
      - lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.event_name == 'pull_request' && github.token || secrets.REPO_TOKEN }}

      - name: Setup
        run: make setup-ci

      - name: Build
        run: make compile

      - name: Test
        run: make test

      - name: Deploy pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/lib/doc/ready-set-vala

  get-release:
    name: Get release for RPM package
    runs-on: als-tiny
    if: github.event_name != 'pull_request'

    outputs:
      release: ${{ steps.get_release.outputs.release }}
    steps:
      - name: Get release
        id: get_release
        run: |
          echo "release=$(date +%s)" >> $FORGEJO_OUTPUT

  rpm-build:
    if: github.event_name != 'pull_request'
    name: RPM build for ${{ matrix.branch }}.${{ matrix.arch }} and uploading
    runs-on: als-huge
    container:
      image: altlinux.space/alt-security/${{ matrix.branch }}/hasher:latest
      options: --platform linux/${{ matrix.arch }}

    strategy:
      matrix:
        branch:
          - sisyphus
          # - p11
        arch:
          - amd64
          # - arm64

    needs:
      - lint
      - get-release

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build
        run: |
          ./build-aux/altlinux/prepare ${{ needs.get-release.outputs.release }}
          git add .

      - name: Build
        run: |
          gear-hsh --commit --no-sisyphus-check=gpg,packager

      - uses: actions/upload-rpm-action@7ed97151a2a1f53a5b97f8a9f20778f771bbae59
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/hasher/repo
          token: ${{ secrets.TOKEN }}
          group: ready-set-nightly/${{ matrix.branch }}
