name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'altlinux'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Check vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  lint-blueprint:
    name: Check blueprint files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/blueprint@main

  checkers:
    name: Run checkers
    runs-on: alt-sisyphus

    steps:
      - name: Update apt cache
        run: apt-get -y update

      - name: Install git and python
        run: apt-get install -y git python3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3 vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3 vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: alt-sisyphus
    needs:
      - lint-vala
      - lint-blueprint
      - checkers

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y meson vala "pkgconfig(gtk4)" "pkgconfig(libadwaita-1)" "pkgconfig(gnome-desktop-4)" "pkgconfig(gee-0.8)" "pkgconfig(accountsservice)" "pkgconfig(ibus-1.0)" "pkgconfig(pwquality)" "pkgconfig(systemd)" "pkgconfig(polkit-gobject-1)" blueprint-compiler
 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build

      - name: Build
        run: meson compile -C _build

  build-altlinux:
    name: Build RPM for altlinux

    runs-on: alt-sisyphus
    container:
      image: altlinux.space/rirusha/riru-build-image:latest
    needs:
      - test-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: alt-gnome/build-rpm-action@main
        name: Build RPMs

      - uses: alt-gnome/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/ready-set/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: ready-set
