ARG IMAGE

FROM $IMAGE

ARG IMAGE
ARG PKG_GROUP

ENV PKG_GROUP=$PKG_GROUP

RUN --mount=type=bind,source=./test-atomic/gnome/image.yml,target=/etc/apm/image.yml \
    --mount=type=bind,source=./test-atomic/gnome/resources,target=/etc/apm/resources \
    apm system image build

WORKDIR /

CMD ["/sbin/init"]
