FROM altlinux.space/alt-atomic/onyx/nightly:latest

RUN --mount=type=bind,source=./test-atomic/gnome/image.yml,target=/etc/apm/image.yml \
    --mount=type=bind,source=./test-atomic/gnome/resources,target=/etc/apm/resources \
    apm system image build
