/* Generated by wayland-scanner 1.25.0 */

#ifndef PHOC_DEVICE_STATE_UNSTABLE_V1_CLIENT_PROTOCOL_H
#define PHOC_DEVICE_STATE_UNSTABLE_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_phoc_device_state_unstable_v1 The phoc_device_state_unstable_v1 protocol
 * @section page_ifaces_phoc_device_state_unstable_v1 Interfaces
 * - @subpage page_iface_zphoc_device_state_v1 - Device state information
 * @section page_copyright_phoc_device_state_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2022 Guido Günther
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 * </pre>
 */
struct zphoc_device_state_v1;

#ifndef ZPHOC_DEVICE_STATE_V1_INTERFACE
#define ZPHOC_DEVICE_STATE_V1_INTERFACE
/**
 * @page page_iface_zphoc_device_state_v1 zphoc_device_state_v1
 * @section page_iface_zphoc_device_state_v1_desc Description
 *
 * This interface provides information about the device state,
 * such as whether a hardware keyboard is attached.
 * @section page_iface_zphoc_device_state_v1_api API
 * See @ref iface_zphoc_device_state_v1.
 */
/**
 * @defgroup iface_zphoc_device_state_v1 The zphoc_device_state_v1 interface
 *
 * This interface provides information about the device state,
 * such as whether a hardware keyboard is attached.
 */
extern const struct wl_interface zphoc_device_state_v1_interface;
#endif

#ifndef ZPHOC_DEVICE_STATE_V1_CAPABILITY_ENUM
#define ZPHOC_DEVICE_STATE_V1_CAPABILITY_ENUM
/**
 * @ingroup iface_zphoc_device_state_v1
 * Device capabilities
 *
 * Bitmask of capabilities present on the device.
 */
enum zphoc_device_state_v1_capability {
	/**
	 * The device has a tablet mode switch
	 */
	ZPHOC_DEVICE_STATE_V1_CAPABILITY_TABLET_MODE_SWITCH = 1,
	/**
	 * The device has a lid switch
	 */
	ZPHOC_DEVICE_STATE_V1_CAPABILITY_LID_SWITCH = 2,
	/**
	 * The device has a hardware keyboard attached
	 * @since 2
	 */
	ZPHOC_DEVICE_STATE_V1_CAPABILITY_KEYBOARD = 4,
};
/**
 * @ingroup iface_zphoc_device_state_v1
 */
#define ZPHOC_DEVICE_STATE_V1_CAPABILITY_KEYBOARD_SINCE_VERSION 2
#endif /* ZPHOC_DEVICE_STATE_V1_CAPABILITY_ENUM */

/**
 * @ingroup iface_zphoc_device_state_v1
 * @struct zphoc_device_state_v1_listener
 */
struct zphoc_device_state_v1_listener {
	/**
	 * Device capabilities changed
	 *
	 * Sent when the device capabilities change. The capabilities
	 * argument is a bitmask of the capability enum values.
	 * @param capabilities bitmask of capabilities
	 */
	void (*capabilities)(void *data,
			     struct zphoc_device_state_v1 *zphoc_device_state_v1,
			     uint32_t capabilities);
};

/**
 * @ingroup iface_zphoc_device_state_v1
 */
static inline int
zphoc_device_state_v1_add_listener(struct zphoc_device_state_v1 *zphoc_device_state_v1,
				   const struct zphoc_device_state_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) zphoc_device_state_v1,
				     (void (**)(void)) listener, data);
}

/**
 * @ingroup iface_zphoc_device_state_v1
 */
#define ZPHOC_DEVICE_STATE_V1_CAPABILITIES_SINCE_VERSION 1


/** @ingroup iface_zphoc_device_state_v1 */
static inline void
zphoc_device_state_v1_set_user_data(struct zphoc_device_state_v1 *zphoc_device_state_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zphoc_device_state_v1, user_data);
}

/** @ingroup iface_zphoc_device_state_v1 */
static inline void *
zphoc_device_state_v1_get_user_data(struct zphoc_device_state_v1 *zphoc_device_state_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zphoc_device_state_v1);
}

static inline uint32_t
zphoc_device_state_v1_get_version(struct zphoc_device_state_v1 *zphoc_device_state_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zphoc_device_state_v1);
}

/** @ingroup iface_zphoc_device_state_v1 */
static inline void
zphoc_device_state_v1_destroy(struct zphoc_device_state_v1 *zphoc_device_state_v1)
{
	wl_proxy_destroy((struct wl_proxy *) zphoc_device_state_v1);
}

#ifdef  __cplusplus
}
#endif

#endif
