FROM altlinux.space/alt-atomic/minimal/phosh/nightly:latest

RUN --mount=type=bind,source=./test-atomic/phosh/image.yml,target=/etc/apm/image.yml \
    --mount=type=bind,source=./test-atomic/phosh/resources,target=/etc/apm/resources \
    apm system image build
