#!/bin/bash
datadir=/usr/libexec/

mkdir -p /run/user/0
chmod 700 /run/user/0
export XDG_RUNTIME_DIR=/run/user/0

# export WAYLAND_DISPLAY=wayland-1

cage $datadir/ready-set-ximper-run &&
# weston -- $datadir/ready-set-ximper-run &&
# phoc -C /usr/share/phosh/phoc.ini -E $datadir/ready-set-ximper-run &&

$datadir/ready-set-ximper-post
