librs_context_mode_sources_internal = files(
  'context-mode-internal.vala',
)

librs_context_raw_sources_internal = files(
  'context-raw-internal.vala',
)

librs_context_loader_sources_internal = files(
  'context-loader-internal.vala',
)

librs_context_vars_sources_internal = files(
  'context-internal.vala',
)

librs_context_sources = files(
  'context.vala',
  'context-object.vala',
)
