#!/usr/bin/bash -ex

# libnma-gtk4.vapi has buggy NMA.WsWpaEap ctor:
# secrets_hints (in C: const char **) became string (instead of string[]?)
# So we fix system vapi file. And copy deps file.

VAPI_DIR="$1"
VAPI_SYS_DIR="$2"

VAPI_FILE="$VAPI_DIR/libnma-gtk4.vapi"
VAPI_SYS_FILE="$VAPI_SYS_DIR/libnma-gtk4.vapi"
DEPS_FILE="$VAPI_DIR/libnma-gtk4.deps"
DEPS_SYS_FILE="$VAPI_SYS_DIR/libnma-gtk4.deps"

sed '/public WsWpaEap/{s/string/[CCode (array_length = false, array_null_terminated = true)] string[]?/}' "$VAPI_SYS_FILE" > "$VAPI_FILE"
cp -f "$DEPS_SYS_FILE" "$DEPS_FILE"
