tuner_plugin_id = 'org.altlinux.ReadySetSoftware.TunerPlugin'
tuner_plugin_pretty_name = 'Third-party Software'
tuner_plugin_name = meson.project_name() + '-software'
tuner_plugin_version = meson.project_version()

gnome = import('gnome')
i18n = import('i18n')

subdir('data')
subdir('src')
subdir('po')
