#!/bin/bash
/usr/libexec/ready-set --steps=language,keyboard,user-with-root

if [ $? -eq 0 ]; then
    if gsettings list-schemas | grep -q "^mobi.phosh.phrog$"; then
        gsettings set mobi.phosh.phrog first-run ""
    fi
fi
