#!/usr/bin/bash -ex

RAW_PATH="test-atomic/vagary/disk.img"
FORCE_REBUILD=false
LOCAL_IMAGE=localhost/ready-set-atomic

sudo rm -f "$RAW_PATH"

TMPDIR=$PWD/.vagary/tmp
mkdir -p $TMPDIR

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force-rebuild) FORCE_REBUILD=true; shift ;;
        *) IMAGE_ARG="$1"; shift ;;
    esac
done

if [[ "$FORCE_REBUILD" == true ]] || ! podman image exists $LOCAL_IMAGE; then
    rm -rf "$RAW_PATH"
    sudo rm -rf "$TMPDIR"/*

    podman build \
        --tag $LOCAL_IMAGE \
        --build-arg "IMAGE=$IMAGE_ARG" \
        --file test-atomic/Containerfile \
        .
fi

truncate -s 15G $RAW_PATH

if [[ "$FORCE_REBUILD" == true ]] || ! sudo podman image exists $LOCAL_IMAGE; then
    podman save "$LOCAL_IMAGE" | sudo env TMPDIR=$TMPDIR podman load
fi

sudo env TMPDIR=$TMPDIR \
    podman run --rm --privileged --pid=host \
        -v /var/lib/containers:/var/lib/containers \
        -v /dev:/dev \
        -v "$PWD:/output" \
        "$LOCAL_IMAGE" \
        bootc install to-disk \
            --generic-image \
            --via-loopback \
            --filesystem ext4 \
            --disable-selinux \
            "/output/$RAW_PATH"
