#!/usr/bin/bash -ex

mkdir -p .gear
cp -a build-aux/altlinux/rules ./.gear/

{
    read -r version;
    read -r soversion;
} < <(./build-aux/get_meson_version)
release=0.$1

sed -e "s/@VERSION@/${version}/g" \
    -e "s/@RELEASE@/${release}/g" \
    -e "s/@SOVERSION@/${soversion}/g" \
    build-aux/altlinux/ready-set.spec.in > ready-set.spec
